# Basic Python

## 1. Split this string

In [3]:
s = "Hi there Sam!"

In [4]:
x=s.split()
print(x)

['Hi', 'there', 'Sam!']


*`italicized text`*## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [5]:
planet = "Earth"
diameter = 12742

In [9]:
x="The diameter of {planet} is {diameter} kilometers".format(planet="Earth",diameter="12742")
print(x)

The diameter of Earth is 12742 kilometers


## 3. In this nest dictionary grab the word "hello"

In [11]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [12]:
d['k1'][3]['tricky'][3]['target'][3]

'hello'

# Numpy

In [13]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [14]:
array=np.zeros(10)
print("An array of 10 zeros")
print(array)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
array=np.ones(10)*5
print("An array of 10 fives")
print(array)

An array of 10 fives
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 5. Create an array of all the even integers from 20 to 35

In [17]:
array=np.arange(20,35,2)
print(array)

[20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [18]:
x =  np.arange(0, 9).reshape(3,3)
print(x)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatinate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [21]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
con = np.concatenate((a, b))
print(con)

[1 2 3 4 5 6]


# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [3]:
import pandas as pd


In [4]:
data = ['Apple','Orange','Grapes']
df = pd.DataFrame(data, columns=['Fruits'])
print(df)

   Fruits
0   Apple
1  Orange
2  Grapes


## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [5]:
dates =pd.date_range(start='01/01/2023',end='10/02/2023', freq='MS')
print(dates)

DatetimeIndex(['2023-01-01', '2023-02-01', '2023-03-01', '2023-04-01',
               '2023-05-01', '2023-06-01', '2023-07-01', '2023-08-01',
               '2023-09-01', '2023-10-01'],
              dtype='datetime64[ns]', freq='MS')


## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [28]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [29]:
data=pd.DataFrame(lists)
print(data)

   0    1   2
0  1  aaa  22
1  2  bbb  25
2  3  ccc  24
